    # # steps:
    # #   - uses: actions/checkout@v3
    # #     name: Check out code

    # #   - uses: mr-smithers-excellent/docker-build-push@v6
    # #     name: Build & push Docker image
    # #     with:
    # #       image: repo/image
    # #       tags: v1, latest
    # #       registry: registry-url.io
    # #       dockerfile: Dockerfile.ci
    # #       username: ${{ secrets.DOCKER_USERNAME }}
    # #       password: ${{ secrets.DOCKER_PASSWORD }}
    # uses: mr-smithers-excellent/docker-build-push@v6
    #       with:
    #       image: docker-hub-repo/image-name
    #       registry: docker.io
    #       username: ${{ secrets.DOCKER_USERNAME }}
    #       password: ${{ secrets.DOCKER_PASSWORD }
name: Build and Push Docker Image


on:
  push:
    branches:
      - main  # Modify this to match your branch name


jobs:
  build_and_push:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build Docker image
        run: docker build -t sample/demo:latest .


      - name: Push Docker image to Docker Hub
        run: docker push 8469552344/demo:latest
