


name: Build and Push Docker Image


on:
  push:
    branches:
      - main  # Modify this to match your branch name


jobs:
  build_and_push:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build Docker image
        run: docker build -t 8469551344/demo:latest ./sample-service


      - name: Push Docker image to Docker Hub
        run: docker push 8469551344/latest 
